server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

spring:
  application:
    name: eurekaserver
  cloud:
    config:
      server:
        git:
          uri: file://home/tamas/projektek/TicketsOnline/ticketsonlinecfg # pt++ : must be in this file or else it won't work

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false        # The inbuilt client will try to fetch the Eureka registry if we configure this property as true (default).
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync