# pt++ : config.server.prefix:  if using Eureka & Config servers in the same program to avoid clash
#        (https://stackoverflow.com/questions/33416103/running-spring-clound-config-and-eureka-on-same-server)
server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

spring:
  application:
    name: eurekaserver
  boot:
    admin:
      context-path: /admin  # pt++ : still won't work A different context path for Spring boot admin server has been provided avoiding conflict with eureka
  cloud:
    config:
      server:
        health:
          config:
            enabled: false
        prefix: /config
        git:
          uri: /home/tamas/projektek/TicketsOnline/ticketsonlinecfg # pt++ : must be in this file or else it won't work

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false        # The inbuilt client will try to fetch the Eureka registry if we configure this property as true (default).
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync

logging:
  level:
    root: INFO