# pt++ : Based on : https://howtodoinjava.com/spring-cloud/spring-cloud-service-discovery-netflix-eureka/
server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started

spring:
  application:
    name: eurekaserverapp
  cloud:
    config:
      server:
        git:
          uri: /home/tamas/projektek/TicketsOnline/ticketsonlinecfg
          #      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
          cloneOnStart: true
    loadbalancer:
      ribbon:
        enabled:false

eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync

management:
  security:
    enabled: false