server:
  port: 8011

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true # https://www.baeldung.com/spring-cloud-netflix-eureka
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true # register with the server (true : default value)
    fetchRegistry: true      # Eureka client will try to fetch registry (true : default value)
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: eventplaceservice
  datasource:
    url: jdbc:h2:mem:eventplacedb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy # pt++ : default : SpringNamingStrategy
  h2:
    console:
      enabled: true
      path: /h2-console
  codec:
    max-in-memory-size: 256KB # pt++ : Spring WebClient Memory limit

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /

hystrix:
  dashboard:
    proxy-stream-allow-list:
      - '*'

logging:
  level:
    root: INFO

  file:
    name: /var/tmp/eventplaceservice.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"
