version: "3.7"

services:
  eurekaserverapp:
#    image: pacsayt/eurekaserverapp
    build: eurekaserverapp
    container_name: eurekaserverapp
    ports:
      - 8761:8761
      - 9411:9411
    working_dir: /opt/eurekaserverapp
    volumes:
      - eurekaserverapp-cfg-dir:/home/tamas/projektek/TicketsOnline/ticketsonlinecfg
      - eurekaserverapp-log-dir:/var/tmp

  eventplaceservice:
#    image: pacsayt/eventplaceservice
    build: eventplaceservice
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI=http://eurekaserverapp:8761/eureka
    ports:
      - 8011:8011
    working_dir: /opt/eventplaceservice
    volumes:
      - eventplaceservice-log-dir:/var/tmp
    depends_on:
      - eurekaserverapp

volumes:
  eurekaserverapp-cfg-dir:
      driver: local
  eurekaserverapp-log-dir:
    driver: local
  eventplaceservice-log-dir:
      driver: local
  eventservice-log-dir:
      driver: local
  ticketservice-log-dir:
      driver: local
  bookedticketservice-log-dir:
      driver: local

